### PR TITLE
Blog pulling in those left behind

### PR DESCRIPTION
**Pull request by psteinb**
imported from http://pad.software-carpentry.org/pulling-along-those-behind

### CODE REVIEW

**Comment by jduckles** [comment]
Can you add some background about the [Discuss] thread as the lead-in? I think it is important to point out this came up as a community mailing list discussion. 

You can also link to the thread in the archives: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-October/thread.html#3396

Otherwise it looks great! Thanks @psteinb and Cam

**Comment by psteinb** [comment]
hi jonah -
so you mean link as on line 12:

```
Given the feedback on the SWC mailing list (see <a href="http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-October/003396.html">original post</a>), this problem occurs quite often. Thus, this blog post is a summary of the discussion initiated among fellow SW
```

should be mentioned earlier?

**Comment by jduckles** [comment]
My bad! Missed it cause of reading along the long-lines you get if there aren't hard-wraps. I'll just check that it builds cleanly and then merge. Thanks for putting this together so fast!

**Comment by psteinb** [comment]
no problem, anytime!
Peter


On 10/29/2015 02:56 PM, Jonah Duckles wrote:
> My bad! Missed it cause of reading along the long-lines you get if there aren't hard-wraps. I'll just check that it builds cleanly and then merge. Thanks for putting this together so fast!
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/swcarpentry/site/pull/1145#issuecomment-152188648
>

-- 
Peter Steinbach, Dr. rer. nat.
HPC Developer, Scientific Computing Facility

Scionics Computer Innovation GmbH
Löscherstr. 16
01309 Dresden
Germany

phone +49 351 210 2882
fax   +49 351 202 707 04
www.scionics.de

Sitz der Gesellschaft: Dresden (Main office)
Amtsgericht - Registergericht: Dresden HRB 20337 (Commercial Registry)
Ust-IdNr.: DE813263791 (VAT ID Number)
Geschäftsführer: John Duperon, Jeff Oegema (Managing Directors)

**Pull request merged**
