### PR TITLE
Add blog announcing selected groups to December Instructor Training

### PR DESCRIPTION
**Pull request by rgaiacs**

### CODE REVIEW

**Comment by jduckles** [comment]
I'll submit a PR back to your fork in a second about the text. but here are comments on the plots.

It isn't quite clear to me what the two plots that you say are the same are intended to show. One is groups one is individuals? They need to be labeled as such with titles perhaps.

The third plot needs changes where:
Man -> Men
Woman -> Women 
was -> were

**Comment by gvwilson** [comment]
I'd advertise the teams' cities rather than their leaders' names.

**Comment by jduckles** [comment]
@gvwilson agreed, I wasn't sure I liked the leader's names being in there either.

**Comment by rgaiacs** [comment]
> I'd advertise the teams' cities rather than their leaders' names.

@gvwilson how do you will solve the problem of cities that had two or more groups but not all were selected.

**Comment by rgaiacs** [comment]
@jduckles Plots updated. Still need to decide about the names.

**Comment by jduckles** [comment]
Please replace them with the city, country of the team.

**Comment by rgaiacs** [comment]
> Please replace them with the city, country of the team.

Done.

**Pull request merged**
