### PR TITLE
Removing direct 'request a DC workshop' link

### PR DESCRIPTION
**Pull request by gvwilson**
1. Remove the direct link to the DC workshop request form.
2. Add a link to the DC website's "request a workshop" explanation.
3. Changing wording to reflect this.

### CODE REVIEW

**Comment by gvwilson** [comment]
@maneesha @tracykteal can you please both review?

**Comment by maneesha** [comment]
I'm generally good with this.  @tracykteal  -- is Data Carpentry going to have a reciprocal "To sign up for a SWC workshop go here...." link?

**Comment by gvwilson** [comment]
Ping @tracykteal

On 2015-10-13 12:53 PM, maneesha sane wrote:
>
> I'm generally good with this. @tracykteal 
> <https://github.com/tracykteal> -- is Data Carpentry going to have a 
> reciprocal "To sign up for a SWC workshop go here...." link?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/pull/1114#issuecomment-147693495>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by tracykteal** [comment]
Thanks, looks good. We'll add a link on our website.

**Pull request closed without merging**
