### PR TITLE
Catching YAML parsing error and reporting it

### PR DESCRIPTION
**Pull request by gvwilson**
Otherwise we don't know which workshop is causing the problem.

### CODE REVIEW

**Comment by gvwilson** [comment]
@pbanaszkiewicz can you please check this as well, and merge it into your branch?

**Comment by pbanaszkiewicz** [comment]
But I think we're not using `bin/workshops.py` anymore, do we? It was used for getting YAML out of `index.html` in workshop repositories, but now we get that YAML compiled from AMY.

**Comment by gvwilson** [comment]
Right.

**Comment by pbanaszkiewicz** [comment]
Does that mean you can close this PR?

**Comment by gvwilson** [comment]
Nope - I'll merge this into master, so that we have it until the new 
AMY-based solution is deployed.

On 2015-08-17 8:46 AM, Piotr Banaszkiewicz wrote:
>
> Does that mean you can close this PR?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/pull/1050#issuecomment-131714577>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Pull request merged**
