### PR TITLE
Replace setup with redirect to workshop template

### PR DESCRIPTION
**Pull request by rgaiacs**
This is a response to @karinlag's [email to discuss mailing list](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-November/003476.html).

### CODE REVIEW

**Comment by jduckles** [comment]
I don't like it like you've proposed. :-1:  You're sending everyone who takes a workshop to a page with FIXME FIXME FIXME at the top, plus a schedule on the page that is notional and probably not right for the workshop they're attending. There is a fair bit of customization that can be done on this page to suit a particular workshop.

Too quick and too dirty to approve like this. I can see what you're trying to do but we need a cleaner solution than what you've proposed.

**Comment by wking** [comment]
I have a bit more free time over the next month or two, so I'll take a
run at wking/swc-setup-installation-test#2.  That will offload some of
the “adjust your installation tests for your workshop” work from the
workshop organizers to the lesson maintainers (workshop managers will
still have to list the lessons they use, but we can do that in the
index.html YAML front matter, which seems to get more attention).

**Comment by karinlag** [comment]
I think this possibly goes into the bigger issue of "website cleanup". IMO, we should only have one version of this page. In this case, I think the best solution is the one that Raniere suggests, but with a bit more explanation on the page referring to the workshop template page, explaining that this is the template used for a workshop, hence the fixmes. Just to have it mentioned, I think we should have this information accessible via the website, we should not require that people have to figure out all of our github stuff (not on their own at least) just to check things out.

**Comment by gvwilson** [comment]
@rgaiacs shall we close this one? I think it's gone stale.

**Pull request closed without merging**
