### PR TITLE
aggregate previous workshops and show in infowindow on cluster click

### PR DESCRIPTION
**Pull request by msarahan**
For previous workshop map, this commit:
- removes the spiderifier completely.  Instead, minimum cluster size is 2, and clustering occurs at all zoom levels.
- on click of a cluster, an info window is displayed that shows previous workshops contained in that cluster, in reverse chronological order
- Disables mouse wheel zooming while an info box is shown, so that the mouse wheel scrolls through info window instead.
- hides info window if zoom changes, since clusters may change completely based on zoom.

### CODE REVIEW

**Comment by gvwilson** [comment]
Nice work!  It looks great - can you do the same with instructors' locations?

**Comment by msarahan** [comment]
For public knowledge, copying comment from email with Greg:

I would like to do the same for the instructor location map, but I need to do more development work on that.  From what I can see, that map's information about location is drawn from _config.yml.  There is no location information associated with instructor names in _config.yml - each airport has only a simple count of people associated with it.  I will be investigating how _config.yml is generated this weekend to see if I can add the appropriate information.

**Comment by timtomch** [comment]
I was looking at the code this morning as I'm interested in creating a similar map for another project, but couldn't figure out where the js maps functions get the `site.workshops` array? If this is documented somewhere, I wasn't able to find it... :(

**Comment by msarahan** [comment]
I think that Jekyll produces this from _config.yml, which is generated from stuff in site/config.  Note that _config.yml doesn't exist in the repository.  It is generated when you make the site.  I hope this points you in the right direction.

**Pull request merged**
