### PR TITLE
Blog post about publishing lessons

### PR DESCRIPTION
**Pull request by gvwilson**
This lists the preferred citation for each lesson, and links to the Zenodo records.

### CODE REVIEW

**Comment by jdblischak** [comment]
+1

**Comment by fmichonneau** [comment]
:+1:

**Comment by douglatornell** [comment]
+1

**Comment by daisieh** [comment]
+1

**Comment by abought** [comment]
Looks good!

**Comment by abought** [comment]
I also went through and confirmed that all of the DOI links go to the correct pages. Very shiny indeed. :shipit:

**Comment by twitwi** [comment]
:shipit:

**Comment by ashwinsrnth** [comment]
Thanks!

**Pull request merged**
