### PR TITLE
SCF 2015 nomination for John Blischak

### PR DESCRIPTION
**Pull request by jdblischak**

### CODE REVIEW

**Comment by wking** [comment]
Typo: “acheiving” → “achieving”.

**Comment by wking** [comment]
I'm not wild about:

  “I'd like to organize small groups of instructors from the same
  scientific field to develop lessons from scratch.”

Would you be open to:

  “I'd like to organize small groups of instructors from the same
  scientific field to develop lessons optimized for their field.”

That leaves “from scratch” out of it, since personally, I think
adapting the current lessons (or at least using them to seed initial
discussion about layout and approach) is going to be more efficient
than throwing that out and starting over.  My suggested wording still
allows greenfield approaches if a group thinks the existing lesson
isn't useful at all, but it doesn't recommend them.

**Comment by gvwilson** [comment]
Thanks John - much appreciated.
- Greg

**Comment by wking** [comment]
On Thu, Jan 15, 2015 at 10:31:32AM -0800, Greg Wilson wrote:
> Merged #735.

And the typo I reported was fixed in 7fa6387dc (Updating John
Blischak's nomination post, 2015-01-15).

**Comment by jdblischak** [comment]
Thanks for the review, @wking.

**Pull request merged**
