### PR TITLE
Add blog post about 13th debriefing session

### PR DESCRIPTION
**Pull request by r-gaia-cs**

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@mckays630 and @ttimbers Could you check review this?

**Comment by ttimbers** [comment]
@r-gaia-cs I will look at this soon.

**Comment by k8hertweck** [comment]
This is great! I forgot that workshop checklist existed, too. In line 23, I think "feel" should be "few"? Thanks for including reminders in this post that if people don't like the materials, they can submit pull requests!

**Comment by ttimbers** [comment]
@r-gaia-cs please see some small grammatical changes I made here: https://github.com/ttimbers/site/blob/master/blog/2015/07/instructor-debriefing-2015-07-17.html

I don't know how to fork your fork, and then send you a pull request, so I just copied your instructor-debriefing-2015-07-17.html file into my fork of the site repo and made my changes there. How should I do this in the future?

**Comment by r-gaia-cs** [comment]
@ttimbers Thanks for the corrections.

t

> I don't know how to fork your fork,

You can't. This is a limitation of GitHub.

> and then send you a pull request,

What you can do is

~~~
$ cd site
$ git remote add raniere git@github.com:r-gaia-cs/site.git
$ git fetch raniere
$ git checkout raniere/debriefing-2015-07-17
$ git checkout -b corrections-to-raniere-post
$ # edit the files
$ git commit -am 'Corrections'
$ git push origin corrections-to-raniere-post
~~~

after this you can go to GitHub's web interface and create a pull request to my fork. **If you want we can schedule to go into the previous steps together.**

> so I just copied your instructor-debriefing-2015-07-17.html file into my fork of the site repo and made my changes there. How should I do this in the future?

This works for me. You can use GitHub's comment feature on pull request. Just goes into the "Files changed" tab of one pull request, find the line with problem, point the mouse to the big of the line and will find a "+" icon. Clicking on the icon you will have a text box to write your comment.

**But I'm happy getting the comments in any format.**

**Comment by ttimbers** [comment]
Thanks for the workflow @r-gaia-cs , makes sense to me and I will do that next time :)

**Comment by gvwilson** [comment]
@r-gaia-cs good to merge?

**Pull request merged**
