### PR TITLE
Create 2016 Election: Belinda Weaver.md

### PR DESCRIPTION
**Pull request by weaverbel**
Proposing to stand for Steering Committee

### CODE REVIEW

**Comment by rgaiacs** [comment]
@weaverbel Could you merge https://github.com/weaverbel/site/pull/1? Thanks.

**Comment by weaverbel** [comment]
?Thanks Raniere.

I did not realise it had to be in blog post format - was that in the instructions? If so, I must have missed it.


Sorry for that and I have merged the fix.


regards
Belinda

Belinda Weaver
eResearch Analyst Team Leader
Queensland Cyber Infrastructure Foundation
Level 5, Axon Building (47)
The University of Queensland
Brisbane AUSTRALIA 4072
e: b.weaver@qcif.edu.au<mailto:b.weaver@uq.edu.au> | p: +617 334 64223 | m: 0408 841 882 | w: www.qcif.edu.au<http://www.qcif.edu.au/> | Twitter @cloudaus<https://twitter.com/cloudaus>
________________________________

**Comment by rgaiacs** [comment]
> I did not realize it had to be in blog post format - was that in the instructions? If so, I must have missed it.

Yes:

> In order to stand for election we request that you write a blog post that introduces yourself to the community ((...)[http://software-carpentry.org/blog/2015/12/call-for-candidates-elections-2016.html])

**Comment by jduckles** [comment]
No worries, @weaverbel it just needed a bit of yaml at the top and to be switched to HTML. In our new version of the site (coming soon) we'll actually be able to do Markdown blog posts with those yaml headers.  Thanks for the submission!

**Comment by jduckles** [comment]
Had to fix this in another PR...closing this one. Should be live shortly.

**Pull request merged**
