### PR TITLE
Writing a more conversational pitch

### PR DESCRIPTION
**Pull request by gvwilson**
Feedback welcome.

### CODE REVIEW

**Comment by gvwilson** [comment]
@jduckles @karinlag comments?

**Comment by jduckles** [comment]
Why are we making the page look like an email template?

I just sent this URL out to a potential partner and I don't think having a template on it helps us. That being said I like the template...maybe move it to the `swcarpentry/board` repo?

**Comment by gvwilson** [comment]
We need something that people can copy, paste, and fill in when they're 
mailing a PI asking for support, and the existing pitch doesn't do 
that.  Want me to put this as a footer to the existing pitch instead of 
as an overwrite?

On 2015-11-30 4:59 PM, Jonah Duckles wrote:
>
> Why are we making the page look like an email template?
>
> I just sent this URL out to a potential partner and I don't think 
> having a template on it helps us. That being said I like the 
> template...maybe move it to the |swcarpentry/board| repo?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/pull/1191#issuecomment-160689769>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by karinlag** [comment]
On 11/30/2015 6:15 PM, Greg Wilson wrote:
> We need something that people can copy, paste, and fill in when they're
> mailing a PI asking for support, and the existing pitch doesn't do
> that. Want me to put this as a footer to the existing pitch instead of
> as an overwrite?

This goes towards something that I have been meaning to mention but 
haven't got around to: I think we should have a "resources" section of 
the site. This one should include pitches to hosts, standard workshop 
advertising blurbs, link to a stripped down version of the install 
instructions and current install difficulties, logos in various formats, 
etc. I also think that the "what is swc" presentations could go here. 
These pages would include stuff that a) instructors and other parties 
would use to pull in a workshop and that are b) reasonably static. Yes, 
I know there are good reasons to have these things in a github repo, but 
when in a hurry (which you usually are) going to the website is a whole 
lot easier to do than to find stuff in gh.

Regarding the pitch itself: the goal is to provide a standard text that 
instructors can use to sell in a workshop. That makes it easier for 
them, and for our part it helps people to not misrepresent us.

Karin

**Comment by gvwilson** [comment]
On 2015-11-30 7:45 PM, karinlag wrote:
> I think we should have a "resources" section of the site.
Yes, and it's been brought up several times, but nobody has volunteered 
yet to write that material.

**Comment by karinlag** [comment]
On 01.12.2015 11:10, Greg Wilson wrote:
> On 2015-11-30 7:45 PM, karinlag wrote:
>  > I think we should have a "resources" section of the site.
> Yes, and it's been brought up several times, but nobody has volunteered
> yet to write that material.

OK. I have sent in a suggestion for a standard ad in the comms repo. We 
have this pitch now, I assume we have logos lying around somewhere? I 
think those things would make a good start?

karin

**Comment by gvwilson** [comment]
The SVG source for our logos is in the admin repo's 'branding' directory 
(and attached), and yeah, those two things would make a good start - thanks.

**Pull request closed without merging**
