### PR TITLE
Add blog post about 20th debriefing session

### PR DESCRIPTION
**Pull request by rgaiacs**
@k8hertweck and @raynamharris Could you review this?

Probably I forgot to mention something from http://pad.software-carpentry.org/swc-debriefing-morning. Please let me know what I missed with comments, one pull request to this branch or with a updated version of this file by email.

### CODE REVIEW

**Comment by k8hertweck** [comment]
@rgaiacs, sent you PR with a few changes. Thanks so much for keeping up with the blog posts!

**Comment by rgaiacs** [comment]
@k8hertweck Sorry for my delay. I'm hoping to merge https://github.com/swcarpentry/site/pull/1124 on October 27th and this one on October 29th.

**Comment by gvwilson** [comment]
Shall I go ahead and merge this now?

**Comment by rgaiacs** [comment]
@gvwilson **Yes**, but could you merge https://github.com/swcarpentry/site/pull/1124 before? **And I think that we need to update the date.**

**Comment by gvwilson** [comment]
Done and done.

**Pull request merged**
