### PR TITLE
Fix Disqus

### PR DESCRIPTION
**Pull request by r-gaia-cs**
Some titles have single quote and because of that we need to use
double quote.

### CODE REVIEW

**Comment by gvwilson** [comment]
Does this restore the comment thread?

**Comment by r-gaia-cs** [comment]
@gvwilson I never could make disqus work when build on my machine. I always get

> We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

It should restore the comment thread. If it didn't we probably will need to contact Disqus support.

**Comment by fmichonneau** [comment]
It might be a side effect of me trying to fix the html tags that showed in the list of recent comments. Before the title were converted in html and the special characters were probably escaped. 

@r-gaia-cs what would happen if the title contains "?

**Comment by gvwilson** [comment]
Yes, you have to be on the server in order for Disqus to load - they 
reverse check to make sure you're not spoofing.

**Comment by r-gaia-cs** [comment]
> It might be a side effect of me trying to fix the html tags that showed in the list of recent comments. Before the title were converted in html and the special characters were probably escaped.

Yes.

To solve this problem and #736 we will have to use something like

~~~
    {% if page.date > Date.parse("2015-03-02") %}
    var disqus_title = "{{ page.title | replace: '"', '' | url_param_escape }}";
    {% else %}
    var disqus_title = '{{page.title | textilize }}'; 
    {% endif %}
~~~

**Unfortunately** the if clause isn't working properly.

**Comment by fmichonneau** [comment]
How about doing it in Javascript?

```
  var page_date = "{{ page.date }}";

    if ( Date.parse(page_date) > Date.parse("2015-02-28") ) {
       var disqus_title = "{{ page.title | replace: '"', ''' | url_param_escape }}";
    } else {
       var disqus_title = '{{page.title | textilize }}';
    }
```

Note that the merge happened on the evening of the 28th, so I changed the date of the test, and I replaced the double quote with a single quote instead of removing everything.

**Pull request merged**
