### PR TITLE
Yet another "Starting conversion to Python 3"

### PR DESCRIPTION
**Pull request by rgaiacs**
Cover #970.

### CODE REVIEW

**Comment by gvwilson** [comment]
I should close #970 ?

**Comment by r-gaia-cs** [comment]
> I should close #970 ?

I merged #970 with `master`, fixed the error when building the website and a few minor changes.

**Comment by gvwilson** [comment]
Gotcha - I'll close #970.

On 2015-07-20 3:29 PM, Raniere Silva wrote:
>
>     I should close #970 <https://github.com/swcarpentry/site/pull/970> ?
>
> I merged #970 <https://github.com/swcarpentry/site/pull/970> with 
> |master|, fixed the error when building the website and a few minor 
> changes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/pull/1031#issuecomment-122998419>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by gvwilson** [comment]
Is this one ready to merge?

**Comment by rgaiacs** [comment]
> Is this one ready to merge?

Yes.

**Comment by gvwilson** [comment]
Replaced by #1084.

**Pull request closed without merging**
