### PR TITLE
Use AMY API

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This PR is based of @rgaiacs work in #1031 (thus so many commits).

This is WIP - should be merged not sooner than corresponding functionality lands in AMY (should be this week).

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
Okay, at this point the website should be able to gather data from AMY.

I have issues with running Jekyll here so please, could someone:
1. grab this and make a site (`make site`)
2. check if everything works
3. tell me what does not work

Thanks in advance.

PS Give it about 2 hours before I update AMY on the server :-)
PPS This is still WIP since I have one more feature to implement (making archives for off-line use).

**Comment by pbanaszkiewicz** [comment]
@gvwilson check this out – the SSL issue should be fixed.

**Comment by gvwilson** [comment]
Cool - the site built!  But it only shows me three upcoming workshops, 
rather than the 17 that show up in the old build (using the 
workshops.yml file).  I need to check whether this is because there are 
a bunch of workshops that aren't yet in AMY - I'll do that and get back 
to you.
Progress!
Thanks,
Greg

**Comment by pbanaszkiewicz** [comment]
We have yet to:
1) fix conflicts :)
2) add a proper "archive" option

Not sure about the upcoming workshops… The idea was that even though some workshops were published from AMY (ie. had their start date and URL), the site should only display a subset of the workshops. Namely these that have: slug, end date, venue, address, latitude, longitude, country, URL, and humandate.

Missing any of these would make them not appear in the upcoming in the site.

**Comment by gvwilson** [comment]
On 2015-08-17 3:37 PM, Piotr Banaszkiewicz wrote:
>
> We have yet to:
> 1) fix conflicts :)
>

I trust you.

> 2) add a proper "archive" option
>

I don't think we need to archive stuff in the Git repo - if people want 
to build the website while they're offline, we can have half a dozen 
dummy workshops' information embedded in the pre-processing script, and 
a command line flag to say, "Pretend you got these from AMY."

> Not sure about the upcoming workshops… The idea was that even though 
> some workshops were published from AMY (ie. had their start date and 
> URL), the site should only display a subset of the workshops. Namely 
> these that have: slug, end date, venue, address, latitude, longitude, 
> country, URL, and humandate.
>
> Missing any of these would make them not appear in the upcoming in the 
> site.
>
I think we can be more relaxed: according to the Event editing page, if 
a workshop has a URL and a startdate, it's published.  I think we should 
extend that to say "URL, country, venue, startdate" for inclusion in the 
data, and then *if* it has a lat/long, we put a pin on the map.

Cheers,
Greg

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by gvwilson** [comment]
Replaced by #1084.

**Pull request closed without merging**
