### PR TITLE
Add redirect page from bootcamps to workshops

### PR DESCRIPTION
**Pull request by rgaiacs**
Addresses  #1040.

### CODE REVIEW

**Comment by gvwilson** [comment]
What about things under `/bootcamp/` ? Would it not be better to add a rule to `.htaccess` (which is stored in the repo as `_htaccess`)?  cc @pipitone

**Comment by pipitone** [comment]
You want `software-carpentry.org/bootcamp` to redirect to `software-carpentry.org/workshops`, but still pages and assets under `/bootcamp/` to be accessible?

**Comment by pipitone** [comment]
If so, a rule in `_htaccess` works fine, is slicker, better for search engines, but definitely more magical and incomprehensible (perhaps okay tho' since we already have rewrite cruft in there). This should do it (untested): 

    RewriteCond %{REQUEST_URI} ^/bootcamp/?$
    RewriteRule ^(.*) /workshops [R,L]

**Comment by rgaiacs** [comment]
> What about things under /bootcamp/ ?

Sorry that I was lazy.

> Would it not be better to add a rule to .htaccess (which is stored in the repo as _htaccess)?

Yes. @gvwilson Can you do that and close this pull request?

**Comment by gvwilson** [comment]
Closed in favor of #1109.

**Pull request closed without merging**
